/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dibujante;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JPopupMenu;

/**
 *
 * @author josearielpereyra
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

        setTitle("Mi Aplicacion de Dibujo");
        setSize(750, 700);
        setLocationRelativeTo(null);

        final PanelDeDibujo panelDeDibujo = new PanelDeDibujo(this);

        add(panelDeDibujo, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonesFiguras = new javax.swing.ButtonGroup();
        ToolBar = new javax.swing.JToolBar();
        BtnG = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        BtLapiz = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        GridColors = new javax.swing.JPanel();
        BLACK = new javax.swing.JToggleButton();
        WHITE = new javax.swing.JToggleButton();
        BLUE = new javax.swing.JToggleButton();
        RED = new javax.swing.JToggleButton();
        YELLOW = new javax.swing.JToggleButton();
        GREEN = new javax.swing.JToggleButton();
        BTcolor = new javax.swing.JButton();
        BtnColorC = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BTlinea = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2_Save2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemLapiz = new javax.swing.JRadioButtonMenuItem();
        menuItemLinea = new javax.swing.JRadioButtonMenuItem();
        menuItemRectangulo = new javax.swing.JRadioButtonMenuItem();
        menuItemRombo = new javax.swing.JRadioButtonMenuItem();
        menuItemCuadrado = new javax.swing.JRadioButtonMenuItem();
        menuItemTrianguloRectangulo = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ToolBar.setRollover(true);

        BtnG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        BtnG.setText("Guardar");
        BtnG.setFocusable(false);
        BtnG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar.add(BtnG);
        ToolBar.add(jSeparator2);

        BtLapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil.png"))); // NOI18N
        BtLapiz.setText("Lapiz");
        BtLapiz.setFocusable(false);
        BtLapiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtLapiz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ToolBar.add(BtLapiz);
        ToolBar.add(jSeparator3);

        GridColors.setLayout(new java.awt.GridLayout(2, 0));

        BLACK.setBackground(new java.awt.Color(0, 0, 0));
        GridColors.add(BLACK);

        WHITE.setBackground(new java.awt.Color(255, 255, 255));
        GridColors.add(WHITE);

        BLUE.setBackground(new java.awt.Color(0, 153, 255));
        BLUE.setPreferredSize(new java.awt.Dimension(28, 28));
        GridColors.add(BLUE);

        RED.setBackground(new java.awt.Color(255, 0, 51));
        GridColors.add(RED);

        YELLOW.setBackground(new java.awt.Color(255, 255, 0));
        GridColors.add(YELLOW);

        GREEN.setBackground(new java.awt.Color(0, 204, 51));
        GridColors.add(GREEN);

        grupoBotonesFiguras.add(BTcolor);
        BTcolor.setFocusable(false);
        BTcolor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BTcolor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GridColors.add(BTcolor);

        ToolBar.add(GridColors);

        BtnColorC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rueda-de-color-2.png"))); // NOI18N
        BtnColorC.setText("Editar Color");
        BtnColorC.setFocusable(false);
        BtnColorC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnColorC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnColorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnColorCActionPerformed(evt);
            }
        });
        ToolBar.add(BtnColorC);
        ToolBar.add(jSeparator4);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/geometric.png"))); // NOI18N
        jLabel2.setText("Figuras");
        ToolBar.add(jLabel2);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        BTlinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        BTlinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTlineaActionPerformed(evt);
            }
        });
        jPanel1.add(BTlinea);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rectangle.png"))); // NOI18N
        jPanel1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rombe.png"))); // NOI18N
        jPanel1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/square.png"))); // NOI18N
        jPanel1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trianglerectangle.png"))); // NOI18N
        jPanel1.add(jButton5);

        ToolBar.add(jPanel1);

        getContentPane().add(ToolBar, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("Archivo");

        jMenuItem2_Save2.setText("Guardar Como...");
        jMenuItem2_Save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_Save2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2_Save2);
        jMenu1.add(jSeparator1);

        jMenuItem1.setText("Salir");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Figuras");

        grupoBotonesFiguras.add(menuItemLapiz);
        menuItemLapiz.setText("Lapiz");
        menuItemLapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil.png"))); // NOI18N
        jMenu2.add(menuItemLapiz);

        grupoBotonesFiguras.add(menuItemLinea);
        menuItemLinea.setText("Linea");
        menuItemLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        jMenu2.add(menuItemLinea);

        grupoBotonesFiguras.add(menuItemRectangulo);
        menuItemRectangulo.setText("Rectangulo");
        menuItemRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rectangle.png"))); // NOI18N
        jMenu2.add(menuItemRectangulo);

        grupoBotonesFiguras.add(menuItemRombo);
        menuItemRombo.setText("Rombo");
        menuItemRombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rombe.png"))); // NOI18N
        jMenu2.add(menuItemRombo);

        grupoBotonesFiguras.add(menuItemCuadrado);
        menuItemCuadrado.setText("Cuadrado");
        menuItemCuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/square.png"))); // NOI18N
        menuItemCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCuadradoActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemCuadrado);

        grupoBotonesFiguras.add(menuItemTrianguloRectangulo);
        menuItemTrianguloRectangulo.setText("Triangulo Rectangulo");
        menuItemTrianguloRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trianglerectangle.png"))); // NOI18N
        menuItemTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTrianguloRectanguloActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemTrianguloRectangulo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCuadradoActionPerformed

    private void menuItemTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTrianguloRectanguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemTrianguloRectanguloActionPerformed

    Color color;
    private void BtnColorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnColorCActionPerformed
        JColorChooser colorP = new JColorChooser();
        color = colorP.showDialog(null, "Selecciona un color para agregar", color.WHITE);
        BTcolor.setBackground(color);
    }//GEN-LAST:event_BtnColorCActionPerformed

    private void jMenuItem2_Save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_Save2ActionPerformed
        System.out.println("Guardando...");
        savefile();
    }//GEN-LAST:event_jMenuItem2_Save2ActionPerformed

    private void BTlineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTlineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTlineaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BLACK;
    private javax.swing.JToggleButton BLUE;
    private javax.swing.JButton BTcolor;
    private javax.swing.JButton BTlinea;
    private javax.swing.JButton BtLapiz;
    private javax.swing.JButton BtnColorC;
    private javax.swing.JButton BtnG;
    private javax.swing.JToggleButton GREEN;
    private javax.swing.JPanel GridColors;
    private javax.swing.JToggleButton RED;
    private javax.swing.JToolBar ToolBar;
    private javax.swing.JToggleButton WHITE;
    private javax.swing.JToggleButton YELLOW;
    private javax.swing.ButtonGroup grupoBotonesFiguras;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2_Save2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JRadioButtonMenuItem menuItemCuadrado;
    private javax.swing.JRadioButtonMenuItem menuItemLapiz;
    private javax.swing.JRadioButtonMenuItem menuItemLinea;
    private javax.swing.JRadioButtonMenuItem menuItemRectangulo;
    private javax.swing.JRadioButtonMenuItem menuItemRombo;
    private javax.swing.JRadioButtonMenuItem menuItemTrianguloRectangulo;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JRadioButtonMenuItem getMenuItemLapiz() {
        return menuItemLapiz;
    }

    public javax.swing.JRadioButtonMenuItem getMenuItemLinea() {
        return menuItemLinea;
    }

    public javax.swing.JRadioButtonMenuItem getMenuItemRectangulo() {
        return menuItemRectangulo;
    }

    public javax.swing.JRadioButtonMenuItem getMenuItemRombo() {
        return menuItemRombo;
    }

    public javax.swing.JRadioButtonMenuItem getMenuItemCuadrado() {
        return menuItemCuadrado;
    }

    public javax.swing.JRadioButtonMenuItem getMenuItemTrianguloRectangulo() {
        return menuItemTrianguloRectangulo;
    }

//Guardar Como

    public void savefile() {
        BufferedImage image2 = new BufferedImage(PanelDeDibujo.WIDTH, PanelDeDibujo.HEIGHT, BufferedImage.TYPE_INT_RGB);

        JFileChooser jFile = new JFileChooser();
        jFile.showSaveDialog(null);

        Path pth = jFile.getSelectedFile().toPath();

        JOptionPane.showMessageDialog(null, "Se guardo en  " + pth.toString());

        Graphics2D graphics2D = image2.createGraphics();
        //PanelDeDibujo.paint(graphics2D);
        try {
            ImageIO.write(image2, "jpeg", new File(pth.toString()));
        } catch (IOException ox) {
            // TODO: handle exception
            ox.printStackTrace();
        }
    }
}
